### ISSUE TITLE
Rails 4 support

### ISSUE THREAD

**Issue by eljojo** [BadrIT/translation_center#30]
Hi,
anyone interested in implementing rails 4 support?

There's the metasearch dependency (https://github.com/BadrIT/translation_center/issues/12) but I took a brief look at the code and the system doesn't support ``strong_parameters`` yet.

I'd be willing to do it if someone else helps me and my free time allows me to do it.

**Comment by sesam** [comment]
@kabdelhady Close this issue? Since front page now says "TranslationCenter works with Rails 4.x onwards. "
