### ISSUE TITLE
rails 4

### ISSUE THREAD

**Issue by christophe-dufour** [BadrIT/translation_center#61]
Hi there,

Is there any project to make translation center working with rails 4?

Regards

**Comment by simplysoft** [comment]
We have made an attempt to make it compatible with rails 4.1 (rails 4.0 is untested so far). It can be found at https://github.com/simplysoft/translation_center

It is still work in progress

**Comment by sesam** [comment]
@kabdelhady Close also this issue? Since front page now says "TranslationCenter works with Rails 4.x onwards. "

**Comment by IslamAzab** [comment]
@sesam Closed
